[Project]
cubic_version = 2026.02.102-release~202602080449~ubuntu24.04.1
first_version = 2026.02.102-release~202602080449~ubuntu24.04.1
create_date = 2026-03-21 22:17
modify_date = 2026-03-21 22:24
directory = /home/shadowbyte/Projects/Cubic Projects/Ribbon OS

[Original]
iso_file_name = linuxmint-22.3-cinnamon-64bit.iso
iso_directory = /home/shadowbyte/Downloads
iso_volume_id = Linux Mint 22.3 Cinnamon 64-bit
iso_release_name = Zena
iso_disk_name = 

[Custom]
iso_version_number = 2026.03.21
iso_file_name = ribbon-os-1.0.0-2026.03.21.iso
iso_directory = /home/shadowbyte/Projects/Cubic Projects/Ribbon OS
iso_volume_id = Ribbon OS 1.0.0 Cinnamon 64-bit
iso_release_name = Blossom
iso_disk_name = Ribbon OS 1.0.0 Cinnamon 64-bit "Blossom"

[Layout]
casper_directory = casper
squashfs_directory = casper
squashfs_file_name = filesystem.squashfs
manifest_file_name = filesystem.manifest
minimal_remove_file_name = 
standard_remove_file_name = filesystem.manifest-remove
size_file_name = filesystem.size
minimal_squashfs_file_name = 
minimal_manifest_file_name = 
minimal_size_file_name = 
standard_squashfs_file_name = 
standard_manifest_file_name = 
standard_size_file_name = 
installer_sources_file_name = 
installer_squashfs_file_name = 
installer_manifest_file_name = 
installer_size_file_name = 
installer_generic_squashfs_file_name = 
installer_generic_manifest_file_name = 
installer_generic_size_file_name = 

[Status]
is_success_analyze = True
is_success_copy = True
is_success_extract = True
iso_template = 789C7D51C16E83300CBDF315B971994BE8DA69E243768D1230D45A885112AAD2AAFFBE84D189D32ED1D3B3F3DEB30D5FA27C5CD9CE232AEA9E650114F8B2184F1D8CC60B007211FD55DBC672ABADEA432303D4E7D0DCD1B34A3D537C5BE1F0027A1A9BF26198A3A2510FA83AF2D846F6CBB39AB48F14891DD4071A87E4F7C7A876B14A5B1A9C60B7E7B9EF0346517FECC94B97FB45FD79DEB301DB5411EFC702727CE8D9B708398A36160B48D1C0A441BE21D01DC5519E3ED789F31C2ACBA8B84C28E44DCA025A5156A966C9CDB72A6B1C5A1D5362B3E75FE060C8A59A63C071B6AB65B1BE605977BF76A78D21D7336C89D0A6C55064D0366EBF30E967540D7E3615F6B46DEA5FED5A1E4F727FBD740E303A743AEED9BC804B1F263B87E207A85CB2EB
iso_checksum = 
iso_checksum_file_name = 

[Options]
update_os_release = True
has_minimal_install = False
boot_configurations = boot/grub/grub.cfg, isolinux/live.cfg
compression = gzip

